--  ============================================================================
--
--         WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.
--
--  This file was generated from Full.idl
--  using RTI Code Generator (rtiddsgen) version 4.7.0.
--  The rtiddsgen tool is part of the RTI Connext DDS distribution.
--  For more information, type 'rtiddsgen -help' at a command shell
--  or consult the Code Generator User's Manual.
--
--  ============================================================================

pragma Extensions_Allowed (On);
with DDS;
with DDS.Sequences_Generic;


pragma Style_Checks (off); --  Since this is autogenerated code.
package  Full is


   type Color is (
         red, 
         green, 
         blue   );
   pragma Convention (C, Color);
   for Color use (
         red => 0 , 
         green => 1 , 
         blue => 2    );
   type Color_Access is access all Color;
   pragma No_Strict_Aliasing (Color_Access);
   type Color_Array is array (Standard.DDS.Natural range <>) of aliased Color;
   pragma Convention (C, Color_Array);
 
   function Color_Get_TypeCode return Standard.DDS.TypeCode_Access;
   pragma Import (C, Color_Get_TypeCode, "Full_Color_get_typecode");

   procedure Initialize (This : in out Color);
   procedure Finalize (This : in out Color);
   procedure Copy (Dst : in out Color;
                   Src : in Color);
                 
   package Color_Seq is new Standard.DDS.Sequences_Generic
   (Full.Color,
    Full.Color_Access,
    Standard.DDS.Natural,
    1,
    Full.Color_Array);               
 
  Kitchen_TypeName : aliased Standard.DDS.String := Standard.DDS.To_DDS_String  ("Full::Kitchen");
   type Kitchen is record
    c : aliased Standard.DDS.Char;    
    wc : aliased Standard.DDS.Wchar;    
    o : aliased Standard.DDS.Octet;    
    b : aliased Standard.DDS.Boolean;    
    f : aliased Standard.DDS.Float;    
    d : aliased Standard.DDS.Double;    
    ld : aliased Standard.DDS.Long_Double;    
    bounded : aliased Standard.DDS.String; --  maximum length = (10)    
    wbounded : aliased Standard.DDS.Wide_String; --  maximum length = (5)    
    rgb : aliased Full.Color;    
   end record;
 
   pragma Convention (C, Kitchen);
   type Kitchen_Access is access all Kitchen;
   pragma No_Strict_Aliasing (Kitchen_Access);
   type Kitchen_Array is array (Standard.DDS.Natural range <>) of aliased Kitchen;
   pragma Convention (C, Kitchen_Array);
 
   function Kitchen_Get_TypeCode return Standard.DDS.TypeCode_Access;
   pragma Import (C, Kitchen_Get_TypeCode, "Full_Kitchen_get_typecode");

   procedure Initialize (This : in out Kitchen);
   procedure Finalize (This : in out Kitchen);
   procedure Copy (Dst : in out Kitchen;
                   Src : in Kitchen);
                 
   package Kitchen_Seq is new Standard.DDS.Sequences_Generic
   (Full.Kitchen,
    Full.Kitchen_Access,
    Standard.DDS.Natural,
    1,
    Full.Kitchen_Array);               

end Full;

