--  ============================================================================
--
--         WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.
--
--  This file was generated from Shapes.idl
--  using RTI Code Generator (rtiddsgen) version 4.7.0.
--  The rtiddsgen tool is part of the RTI Connext DDS distribution.
--  For more information, type 'rtiddsgen -help' at a command shell
--  or consult the Code Generator User's Manual.
--
--  ============================================================================

pragma Extensions_Allowed (On);
with DDS;
with DDS.Sequences_Generic;


pragma Style_Checks (off); --  Since this is autogenerated code.
package  Shapes is


   type Color is (
         red, 
         green, 
         blue   );
   pragma Convention (C, Color);
   for Color use (
         red => 0 , 
         green => 1 , 
         blue => 2    );
   type Color_Access is access all Color;
   pragma No_Strict_Aliasing (Color_Access);
   type Color_Array is array (Standard.DDS.Natural range <>) of aliased Color;
   pragma Convention (C, Color_Array);
 
   function Color_Get_TypeCode return Standard.DDS.TypeCode_Access;
   pragma Import (C, Color_Get_TypeCode, "Shapes_Color_get_typecode");

   procedure Initialize (This : in out Color);
   procedure Finalize (This : in out Color);
   procedure Copy (Dst : in out Color;
                   Src : in Color);
                 
   package Color_Seq is new Standard.DDS.Sequences_Generic
   (Shapes.Color,
    Shapes.Color_Access,
    Standard.DDS.Natural,
    1,
    Shapes.Color_Array);               
 
  Point_TypeName : aliased Standard.DDS.String := Standard.DDS.To_DDS_String  ("Shapes::Point");
   type Point is record
    x : aliased Standard.DDS.Long;    
    y : aliased Standard.DDS.Long;    
   end record;
 
   pragma Convention (C, Point);
   type Point_Access is access all Point;
   pragma No_Strict_Aliasing (Point_Access);
   type Point_Array is array (Standard.DDS.Natural range <>) of aliased Point;
   pragma Convention (C, Point_Array);
 
   function Point_Get_TypeCode return Standard.DDS.TypeCode_Access;
   pragma Import (C, Point_Get_TypeCode, "Shapes_Point_get_typecode");

   procedure Initialize (This : in out Point);
   procedure Finalize (This : in out Point);
   procedure Copy (Dst : in out Point;
                   Src : in Point);
                 
   package Point_Seq is new Standard.DDS.Sequences_Generic
   (Shapes.Point,
    Shapes.Point_Access,
    Standard.DDS.Natural,
    1,
    Shapes.Point_Array);               
 
  Polygon_TypeName : aliased Standard.DDS.String := Standard.DDS.To_DDS_String  ("Shapes::Polygon");
   type Polygon is record
    name : aliased Standard.DDS.String; --  maximum length = (255)    
    fill : aliased Shapes.Color;    
    corners : aliased  Shapes.Point_Array(1..4);
    lengths : aliased  Standard.DDS.Long_Seq.Sequence;
    weights : aliased  Standard.DDS.Double_Seq.Sequence;
    depth : aliased Standard.DDS.Unsigned_Short;    
   end record;
 
   pragma Convention (C, Polygon);
   type Polygon_Access is access all Polygon;
   pragma No_Strict_Aliasing (Polygon_Access);
   type Polygon_Array is array (Standard.DDS.Natural range <>) of aliased Polygon;
   pragma Convention (C, Polygon_Array);
 
   function Polygon_Get_TypeCode return Standard.DDS.TypeCode_Access;
   pragma Import (C, Polygon_Get_TypeCode, "Shapes_Polygon_get_typecode");

   procedure Initialize (This : in out Polygon);
   procedure Finalize (This : in out Polygon);
   procedure Copy (Dst : in out Polygon;
                   Src : in Polygon);
                 
   package Polygon_Seq is new Standard.DDS.Sequences_Generic
   (Shapes.Polygon,
    Shapes.Polygon_Access,
    Standard.DDS.Natural,
    1,
    Shapes.Polygon_Array);               

end Shapes;

