------------------------------------------------------------------------------
--  IDL2Lang.Tests.Codegen -- byte-parity tests against rtiddsgen output
--
--  Goal.txt requirement 5: generate the same output files with the
--  same contents as rtiddsgen.  The reference files live in
--  test/data/oracle_ada (generated by rtiddsgen 4.7.0 from Hello.idl
--  with "-language Ada -create typefiles -ppDisable").
--
--  The parity primitive: run the factory's Ada back-end over the IDL
--  text, then compare each emitted file's in-memory contents with the
--  oracle file on disk byte by byte.
--
--  Note: socket-style fixtures must live at library level (GNAT
--  pitfall #5); the oracle directory path is a library-level constant.
------------------------------------------------------------------------------

with AUnit;
with AUnit.Test_Cases;

package IDL2Lang.Tests.Codegen is

   type Codegen_Test is new AUnit.Test_Cases.Test_Case with null record;

   overriding procedure Register_Tests (T : in out Codegen_Test);
   overriding function Name (T : Codegen_Test) return AUnit.Message_String;

end IDL2Lang.Tests.Codegen;