--  ============================================================================
--
--         WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.
--
--  This file was generated from HelloWorld.idl
--  using RTI Code Generator (rtiddsgen) version 4.7.0.
--  The rtiddsgen tool is part of the RTI Connext DDS distribution.
--  For more information, type 'rtiddsgen -help' at a command shell
--  or consult the Code Generator User's Manual.
--
--  ============================================================================

pragma Extensions_Allowed (On);
with DDS;


pragma Style_Checks (off); --  Since this is autogenerated code.
package  HelloWorld_IDL_File is


HELLO_MAX_STRING_SIZE : constant Standard.DDS.Long := 256;

end HelloWorld_IDL_File;

