--  ============================================================================
--
--         WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.
--
--  This file was generated from HelloWorld.idl
--  using RTI Code Generator (rtiddsgen) version 4.7.0.
--  The rtiddsgen tool is part of the RTI Connext DDS distribution.
--  For more information, type 'rtiddsgen -help' at a command shell
--  or consult the Code Generator User's Manual.
--
--  ============================================================================

pragma Extensions_Allowed (On);
with DDS;
with DDS.Sequences_Generic;


pragma Style_Checks (off); --  Since this is autogenerated code.
package  testCodeGen is

 
  HelloWorld_TypeName : aliased Standard.DDS.String := Standard.DDS.To_DDS_String  ("testCodeGen::HelloWorld");
   type HelloWorld is record
    message : aliased Standard.DDS.String; --  maximum length = ((HELLO_MAX_STRING_SIZE))    
    value : aliased Standard.DDS.Double;    
   end record;
 
   pragma Convention (C, HelloWorld);
   type HelloWorld_Access is access all HelloWorld;
   pragma No_Strict_Aliasing (HelloWorld_Access);
   type HelloWorld_Array is array (Standard.DDS.Natural range <>) of aliased HelloWorld;
   pragma Convention (C, HelloWorld_Array);
 
   function HelloWorld_Get_TypeCode return Standard.DDS.TypeCode_Access;
   pragma Import (C, HelloWorld_Get_TypeCode, "testCodeGen_HelloWorld_get_typecode");

   procedure Initialize (This : in out HelloWorld);
   procedure Finalize (This : in out HelloWorld);
   procedure Copy (Dst : in out HelloWorld;
                   Src : in HelloWorld);
                 
   package HelloWorld_Seq is new Standard.DDS.Sequences_Generic
   (testCodeGen.HelloWorld,
    testCodeGen.HelloWorld_Access,
    Standard.DDS.Natural,
    1,
    testCodeGen.HelloWorld_Array);               

end testCodeGen;

