--  ============================================================================
--
--         WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.
--
--  This file was generated from HelloWorld.idl
--  using RTI Code Generator (rtiddsgen) version 4.7.0.
--  The rtiddsgen tool is part of the RTI Connext DDS distribution.
--  For more information, type 'rtiddsgen -help' at a command shell
--  or consult the Code Generator User's Manual.
--
--  ============================================================================

pragma Extensions_Allowed (On);
pragma Warnings (Off); --  Since this is autogenerated code.
pragma Style_Checks (off);

with Ada.Unchecked_Conversion;

with DDS.Builtin_Octets_TypeSupport;
with DDS.DomainParticipant_Impl;

with Interfaces.C.Strings;

with RTIDDS.Low_Level.ndds_dds_c_dds_c_builtin_h;
with RTIDDS.Low_Level.ndds_dds_c_dds_c_domain_h;
with RTIDDS.Low_Level.ndds_dds_c_dds_c_domain_impl_h;
with RTIDDS.Low_Level.ndds_dds_c_dds_c_octet_buffer_h;
with RTIDDS.Low_Level.ndds_dds_c_dds_c_string_h;
with RTIDDS.Low_Level.ndds_osapi_osapi_alignment_impl_h;
with RTIDDS.Low_Level.ndds_pres_pres_common_h;
with RTIDDS.Low_Level.ndds_pres_pres_typePlugin_h;

with testCodeGen.HelloWorld_DataReader;
with testCodeGen.HelloWorld_DataWriter;

package body testCodeGen.HelloWorld_TypeSupport is

   use RTIDDS.Low_Level.ndds_dds_c_dds_c_domain_impl_h;
   use RTIDDS.Low_Level.ndds_dds_c_dds_c_domain_h;
   use RTIDDS.Low_Level.ndds_pres_pres_typePlugin_h;
   use RTIDDS.Low_Level.ndds_osapi_osapi_alignment_impl_h;
   use RTIDDS.Low_Level.ndds_dds_c_dds_c_builtin_h;
   use RTIDDS.Low_Level.ndds_dds_c_dds_c_string_h;

   The_Instance : aliased Ref;
   Instance_Ref : constant Standard.DDS.TypeSupport.Ref_Access := The_Instance'Access;

   function Create_TypedDataReaderI
     (Self : access Ref) return Standard.DDS.DataReader.Ref_Access is
   begin
      return testCodeGen.HelloWorld_DataReader.CreateTypedI;
   end  Create_TypedDataReaderI;

   procedure Destroy_TypedDataReaderI
     (Self   : access Ref;
      Reader : in out Standard.DDS.DataReader.Ref_Access) is
   begin
      testCodeGen.HelloWorld_DataReader.DestroyTypedI (Reader);
   end  Destroy_TypedDataReaderI;

   function Create_TypedDataWriterI
     (Self : access Ref) return Standard.DDS.DataWriter.Ref_Access is
   begin
      return testCodeGen.HelloWorld_DataWriter.CreateTypedI;
   end  Create_TypedDataWriterI;

   procedure Destroy_TypedDataWriterI
     (Self   : access Ref;
      Writer : in out Standard.DDS.DataWriter.Ref_Access) is
   begin
      Writer := null;
   end Destroy_TypedDataWriterI;

   function Get_Native_Typesupport_Ptr
     (DeleteInstance : Standard.DDS.Boolean)
     return System.Address;
   pragma Import (C, Get_Native_Typesupport_Ptr, "testCodeGen_HelloWorldTypeSupport_get_or_delete_instanceI");

   function R_To_A is new Ada.Unchecked_Conversion
     (Source => Ref_Access,
      Target => System.Address);

   procedure Set_User_Data
     (Self : System.Address; User_Data : System.Address);
   pragma Import (C, Set_User_Data,                  "DDS_DataTypeUtility_set_user_dataI");

   -------------------
   -- Register_Type --
   -------------------

   procedure Register_Type
     (Participant : not null access Standard.DDS.DomainParticipant.Ref'Class;
      Type_Name   : in Standard.DDS.String) is

      P : constant Standard.DDS.DomainParticipant_Impl.Ref_Access :=
            Standard.DDS.DomainParticipant_Impl.Ref_Access (Participant);

      function InternalCreatePlugin
         return access PRESTypePlugin;
      pragma Import (C, InternalCreatePlugin, "testCodeGen_HelloWorldPlugin_new");

      procedure InternalDeletePlugin
        (plugin : access PRESTypePlugin);
      pragma Import (C, InternalDeletePlugin, "testCodeGen_HelloWorldPlugin_delete");

      function InternalRegister
        (Participant : System.Address;
         Type_Name   : in Interfaces.C.Strings.chars_ptr;
         InternalPresTypePlugin : System.Address;
         Registration_Data : in System.Address)
         return Standard.DDS.ReturnCode_T;
      pragma Import (C, InternalRegister, "DDS_DomainParticipant_register_type");

      C_DataTypeUtility_Ptr : access PRESTypePlugin;
      InternalTypePlugin : access PRESTypePlugin;
      type TempT is access all RTIDDS.Low_Level.ndds_pres_pres_common_h.PRESWord;
      function convert is new Ada.Unchecked_Conversion (Standard.DDS.TypeSupport.Ref_Access, TempT);
      Code                  : Standard.dds.ReturnCode_T;
   begin
      InternalTypePlugin := InternalCreatePlugin;
      InternalTypePlugin.all.U_UserBuffer := Convert (Instance_Ref).all'Unrestricted_Access;
      Code := InternalRegister (P.GetInterface, Type_Name.Data, InternalTypePlugin.all'Address, System.Null_Address);
      Standard.DDS.Ret_Code_To_Exception (Code, "unable to register type");
      InternalDeletePlugin (InternalTypePlugin);
   end Register_Type;

   procedure Register_Type (Participant :  not null access Standard.DDS.DomainParticipant.Ref'Class) is
   begin
      Register_Type (Participant, Get_Type_Name);
   end;
   -------------------
   -- Unregister_Type --
   -------------------

   procedure Unregister_Type
     (Participant : not null access Standard.DDS.DomainParticipant.Ref'Class;
      Type_Name   : in Standard.DDS.String) is

      function Internal
        (Participant : System.Address;
         Type_Name   : in Interfaces.C.Strings.chars_ptr)
         return Standard.DDS.ReturnCode_T;
      pragma Import (C, Internal, "testCodeGen_HelloWorldTypeSupport_unregister_type");

      Code                  : Standard.Dds.ReturnCode_T;
   begin
         Code := Internal (Participant.GetInterface, Type_Name.Data);
         Standard.DDS.Ret_Code_To_Exception
           (Code, "unable to unregister type");
   end Unregister_Type;

   -------------------
   -- Get_Type_Name --
   -------------------

   function Get_Type_Name
     return Standard.DDS.String is
      function Internal return Interfaces.C.Strings.chars_ptr;
      pragma Import (C, Internal, "testCodeGen_HelloWorldTypeSupport_get_type_name");
   begin
      return Name : Standard.DDS.String do
         Name.Data := DDS_String_dup (Internal);
      end return;
   end Get_Type_Name;

   -----------------
   -- Create_Data --
   -----------------

   function Create_Data
     (AllocatePointers : in Boolean := True)
      return not null HelloWorld_Access
   is
      function Internal (AllocatePointers : in Boolean)
                         return HelloWorld_Access;
      pragma Import (C, Internal, "testCodeGen_HelloWorldTypeSupport_create_data_ex");
      Ret : HelloWorld_Access;
   begin
      Ret := Internal (AllocatePointers);
      if Ret = null then
         raise Storage_Error with "Unable to create " & "HelloWorld";
      else
         return Ret;
      end if;
   end Create_Data;

   -----------------
   -- Delete_Data --
   -----------------

   procedure Delete_Data
     (A_Data         : in out HelloWorld_Access;
      DeletePointers : in Boolean := True)
   is
      function Internal (A_Data         : in HelloWorld_Access;
                         DeletePointers : in Boolean := True)
                         return Standard.DDS.ReturnCode_T;
      pragma Import (C, Internal, "testCodeGen_HelloWorldTypeSupport_delete_data_ex");
   begin
      Standard.DDS.Ret_Code_To_Exception
        (Internal (A_Data, DeletePointers),
         "Unable to delete data");
      A_Data := null;
   end Delete_Data;

   ----------------
   -- Print_Data --
   ----------------

   procedure Print_Data
     (A_Data : not null access constant HelloWorld)
   is
      procedure Internal (A_Data : not null access constant HelloWorld);
      pragma Import (C, Internal, "testCodeGen_HelloWorldTypeSupport_print_data");
   begin
      Internal (A_Data);
   end Print_Data;

   ---------------
   -- Copy_Data --
   ---------------

   procedure Copy_Data
     (Dest   : not null access HelloWorld;
      Source : not null access constant HelloWorld)
   is
      function Internal (Dest   : not null access HelloWorld;
                         Source : not null access constant HelloWorld)
                         return Standard.DDS.ReturnCode_T;
      pragma Import (C, Internal, "testCodeGen_HelloWorldTypeSupport_copy_data");
   begin
      Standard.DDS.Ret_Code_To_Exception
        (Internal (Dest, Source),
         "Unable to copy data");
   end Copy_Data;

   ---------------------
   -- Initialize_Data --
   ---------------------

   procedure Initialize_Data
     (Dest             : not null access HelloWorld;
      AllocatePointers : in Boolean := True)
   is
      function Internal (Dest             : not null access HelloWorld;
                         AllocatePointers : in Boolean := True)
                         return Standard.DDS.ReturnCode_T;
      pragma Import (C, Internal, "testCodeGen_HelloWorldTypeSupport_initialize_data_ex");
   begin
      Standard.DDS.Ret_Code_To_Exception
        (Internal (Dest, AllocatePointers),
         "Unable to initialize data");
   end Initialize_Data;

   -------------------
   -- Finalize_Data --
   -------------------

   procedure Finalize_Data
     (Dest           : not null access HelloWorld;
      DeletePointers : in Boolean := True)
   is
      function Internal (Dest           : not null access HelloWorld;
                         DeletePointers : in Boolean := True)
                         return Standard.DDS.ReturnCode_T;
      pragma Import (C, Internal, "testCodeGen_HelloWorldTypeSupport_finalize_data_ex");
   begin
      Standard.DDS.Ret_Code_To_Exception
        (Internal (Dest, DeletePointers),
         "Unable to finalize data");
   end Finalize_Data;

   --------------
   -- Finalize --
   --------------

   procedure Finalize is
      function Internal return Standard.DDS.ReturnCode_T;
      pragma Import (C, Internal, "testCodeGen_HelloWorldTypeSupport_finalize");
   begin
      Standard.DDS.Ret_Code_To_Exception (Internal, "Unable to finalize");
   end Finalize;

begin
   Standard.DDS.DomainParticipant_Impl.Register_Type_Registration (Register_Type'Access);
end testCodeGen.HelloWorld_TypeSupport;
