--  ============================================================================
--
--         WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.
--
--  This file was generated from Demo.idl
--  using RTI Code Generator (rtiddsgen) version 4.7.0.
--  The rtiddsgen tool is part of the RTI Connext DDS distribution.
--  For more information, type 'rtiddsgen -help' at a command shell
--  or consult the Code Generator User's Manual.
--
--  ============================================================================

pragma Extensions_Allowed (On);
with DDS;
with DDS.Sequences_Generic;


pragma Style_Checks (off); --  Since this is autogenerated code.
package  com.saabgroup.enterprisebus.idldemo is

 
  MyStruct_TypeName : aliased Standard.DDS.String := Standard.DDS.To_DDS_String  ("com::saabgroup::enterprisebus::idldemo::MyStruct");
   type MyStruct is record
    X : aliased Standard.DDS.Long;    
    Y : aliased Standard.DDS.Long;    
    Z : aliased Standard.DDS.Long;    
   end record;
 
   pragma Convention (C, MyStruct);
   type MyStruct_Access is access all MyStruct;
   pragma No_Strict_Aliasing (MyStruct_Access);
   type MyStruct_Array is array (Standard.DDS.Natural range <>) of aliased MyStruct;
   pragma Convention (C, MyStruct_Array);
 
   function MyStruct_Get_TypeCode return Standard.DDS.TypeCode_Access;
   pragma Import (C, MyStruct_Get_TypeCode, "com_saabgroup_enterprisebus_idldemo_MyStruct_get_typecode");

   procedure Initialize (This : in out MyStruct);
   procedure Finalize (This : in out MyStruct);
   procedure Copy (Dst : in out MyStruct;
                   Src : in MyStruct);
                 
   package MyStruct_Seq is new Standard.DDS.Sequences_Generic
   (com.saabgroup.enterprisebus.idldemo.MyStruct,
    com.saabgroup.enterprisebus.idldemo.MyStruct_Access,
    Standard.DDS.Natural,
    1,
    com.saabgroup.enterprisebus.idldemo.MyStruct_Array);               

   type Variants is (
         Var1, 
         Var2, 
         Var3   );
   pragma Convention (C, Variants);
   for Variants use (
         Var1 => 0 , 
         Var2 => 1 , 
         Var3 => 2    );
   type Variants_Access is access all Variants;
   pragma No_Strict_Aliasing (Variants_Access);
   type Variants_Array is array (Standard.DDS.Natural range <>) of aliased Variants;
   pragma Convention (C, Variants_Array);
 
   function Variants_Get_TypeCode return Standard.DDS.TypeCode_Access;
   pragma Import (C, Variants_Get_TypeCode, "com_saabgroup_enterprisebus_idldemo_Variants_get_typecode");

   procedure Initialize (This : in out Variants);
   procedure Finalize (This : in out Variants);
   procedure Copy (Dst : in out Variants;
                   Src : in Variants);
                 
   package Variants_Seq is new Standard.DDS.Sequences_Generic
   (com.saabgroup.enterprisebus.idldemo.Variants,
    com.saabgroup.enterprisebus.idldemo.Variants_Access,
    Standard.DDS.Natural,
    1,
    com.saabgroup.enterprisebus.idldemo.Variants_Array);               
 
  Demo_TypeName : aliased Standard.DDS.String := Standard.DDS.To_DDS_String  ("com::saabgroup::enterprisebus::idldemo::Demo");
   type U_Demo is record
    aStruct : aliased com.saabgroup.enterprisebus.idldemo.MyStruct;    
    aBoolean : aliased Standard.DDS.Boolean;    
    aLong : aliased Standard.DDS.Long;    
    aDouble : aliased Standard.DDS.Double;    
   end record;
     pragma Convention (C, U_Demo);
 
    type Demo is record
     d : Standard.DDS.Long;
     u : U_Demo;
    end record;
 
   pragma Convention (C, Demo);
   type Demo_Access is access all Demo;
   pragma No_Strict_Aliasing (Demo_Access);
   type Demo_Array is array (Standard.DDS.Natural range <>) of aliased Demo;
   pragma Convention (C, Demo_Array);
 
   function Demo_Get_TypeCode return Standard.DDS.TypeCode_Access;
   pragma Import (C, Demo_Get_TypeCode, "com_saabgroup_enterprisebus_idldemo_Demo_get_typecode");

   procedure Initialize (This : in out Demo);
   procedure Finalize (This : in out Demo);
   procedure Copy (Dst : in out Demo;
                   Src : in Demo);
                 
   package Demo_Seq is new Standard.DDS.Sequences_Generic
   (com.saabgroup.enterprisebus.idldemo.Demo,
    com.saabgroup.enterprisebus.idldemo.Demo_Access,
    Standard.DDS.Natural,
    1,
    com.saabgroup.enterprisebus.idldemo.Demo_Array);               

end com.saabgroup.enterprisebus.idldemo;

