--  ============================================================================
--
--         WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.
--
--  This file was generated from ArrayRanges.idl
--  using RTI Code Generator (rtiddsgen) version 4.7.0.
--  The rtiddsgen tool is part of the RTI Connext DDS distribution.
--  For more information, type 'rtiddsgen -help' at a command shell
--  or consult the Code Generator User's Manual.
--
--  ============================================================================

pragma Extensions_Allowed (On);
with DDS;
with DDS.Sequences_Generic;


pragma Style_Checks (off); --  Since this is autogenerated code.
package  hello is


SIZE : constant Standard.DDS.Long := 10;
 
  World_T_TypeName : aliased Standard.DDS.String := Standard.DDS.To_DDS_String  ("hello::World_T");
   type World_T is record
    data : aliased Standard.DDS.Long;    
   end record;
 
   pragma Convention (C, World_T);
   type World_T_Access is access all World_T;
   pragma No_Strict_Aliasing (World_T_Access);
   type World_T_Array is array (Standard.DDS.Natural range <>) of aliased World_T;
   pragma Convention (C, World_T_Array);
 
   function World_T_Get_TypeCode return Standard.DDS.TypeCode_Access;
   pragma Import (C, World_T_Get_TypeCode, "hello_World_T_get_typecode");

   procedure Initialize (This : in out World_T);
   procedure Finalize (This : in out World_T);
   procedure Copy (Dst : in out World_T;
                   Src : in World_T);
                 
   package World_T_Seq is new Standard.DDS.Sequences_Generic
   (hello.World_T,
    hello.World_T_Access,
    Standard.DDS.Natural,
    1,
    hello.World_T_Array);               
 
  HelloWorld_TypeName : aliased Standard.DDS.String := Standard.DDS.To_DDS_String  ("hello::HelloWorld");
   type HelloWorld is record
    msg : aliased Standard.DDS.String; --  maximum length = (128)    
    worlds_1 : aliased  hello.World_T_Array(1..(hello.SIZE));
    worlds_2 : aliased  hello.World_T_Array(1..24);
    profile_1 : aliased  Standard.DDS.Boolean_Array(1..24);
    profile_2 : aliased  Standard.DDS.Boolean_Array(1..(hello.SIZE));
   end record;
 
   pragma Convention (C, HelloWorld);
   type HelloWorld_Access is access all HelloWorld;
   pragma No_Strict_Aliasing (HelloWorld_Access);
   type HelloWorld_Array is array (Standard.DDS.Natural range <>) of aliased HelloWorld;
   pragma Convention (C, HelloWorld_Array);
 
   function HelloWorld_Get_TypeCode return Standard.DDS.TypeCode_Access;
   pragma Import (C, HelloWorld_Get_TypeCode, "hello_HelloWorld_get_typecode");

   procedure Initialize (This : in out HelloWorld);
   procedure Finalize (This : in out HelloWorld);
   procedure Copy (Dst : in out HelloWorld;
                   Src : in HelloWorld);
                 
   package HelloWorld_Seq is new Standard.DDS.Sequences_Generic
   (hello.HelloWorld,
    hello.HelloWorld_Access,
    Standard.DDS.Natural,
    1,
    hello.HelloWorld_Array);               

end hello;

