--  ============================================================================
--
--         WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.
--
--  This file was generated from sequences.idl
--  using RTI Code Generator (rtiddsgen) version 4.7.0.
--  The rtiddsgen tool is part of the RTI Connext DDS distribution.
--  For more information, type 'rtiddsgen -help' at a command shell
--  or consult the Code Generator User's Manual.
--
--  ============================================================================

pragma Extensions_Allowed (On);
with DDS;
with DDS.Sequences_Generic;


pragma Style_Checks (off); --  Since this is autogenerated code.
package  com.rti.tests.DdsTopics.EngagementControl.ZonedThreatList is

 
  Key_TypeName : aliased Standard.DDS.String := Standard.DDS.To_DDS_String  ("com::rti::tests::DdsTopics::EngagementControl::ZonedThreatList::Key");
   type Key is record
    numberOfThreats : aliased Standard.DDS.Long;    
   end record;
 
   pragma Convention (C, Key);
   type Key_Access is access all Key;
   pragma No_Strict_Aliasing (Key_Access);
   type Key_Array is array (Standard.DDS.Natural range <>) of aliased Key;
   pragma Convention (C, Key_Array);
 
   function Key_Get_TypeCode return Standard.DDS.TypeCode_Access;
   pragma Import (C, Key_Get_TypeCode, "com_rti_tests_DdsTopics_EngagementControl_ZonedThreatList_Key_get_typecode");

   procedure Initialize (This : in out Key);
   procedure Finalize (This : in out Key);
   procedure Copy (Dst : in out Key;
                   Src : in Key);
                 
   package Key_Seq is new Standard.DDS.Sequences_Generic
   (com.rti.tests.DdsTopics.EngagementControl.ZonedThreatList.Key,
    com.rti.tests.DdsTopics.EngagementControl.ZonedThreatList.Key_Access,
    Standard.DDS.Natural,
    1,
    com.rti.tests.DdsTopics.EngagementControl.ZonedThreatList.Key_Array);               

ZONED_THREAT_LIST_MAXSIZE : constant Standard.DDS.Long := 10;
 
  ZonedThreatList_TypeName : aliased Standard.DDS.String := Standard.DDS.To_DDS_String  ("com::rti::tests::DdsTopics::EngagementControl::ZonedThreatList::ZonedThreatList");
   type ZonedThreatList is record
    numberOfThreats : aliased Standard.DDS.Long;    
    zonedThreats : aliased  com.rti.tests.DdsTopics.EngagementControl.ZonedThreatList.Key_Seq.Sequence;
   end record;
 
   pragma Convention (C, ZonedThreatList);
   type ZonedThreatList_Access is access all ZonedThreatList;
   pragma No_Strict_Aliasing (ZonedThreatList_Access);
   type ZonedThreatList_Array is array (Standard.DDS.Natural range <>) of aliased ZonedThreatList;
   pragma Convention (C, ZonedThreatList_Array);
 
   function ZonedThreatList_Get_TypeCode return Standard.DDS.TypeCode_Access;
   pragma Import (C, ZonedThreatList_Get_TypeCode, "com_rti_tests_DdsTopics_EngagementControl_ZonedThreatList_ZonedThreatList_get_typecode");

   procedure Initialize (This : in out ZonedThreatList);
   procedure Finalize (This : in out ZonedThreatList);
   procedure Copy (Dst : in out ZonedThreatList;
                   Src : in ZonedThreatList);
                 
   package ZonedThreatList_Seq is new Standard.DDS.Sequences_Generic
   (com.rti.tests.DdsTopics.EngagementControl.ZonedThreatList.ZonedThreatList,
    com.rti.tests.DdsTopics.EngagementControl.ZonedThreatList.ZonedThreatList_Access,
    Standard.DDS.Natural,
    1,
    com.rti.tests.DdsTopics.EngagementControl.ZonedThreatList.ZonedThreatList_Array);               

end com.rti.tests.DdsTopics.EngagementControl.ZonedThreatList;

