--  ============================================================================
--
--         WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.
--
--  This file was generated from Constants.idl
--  using RTI Code Generator (rtiddsgen) version 4.7.0.
--  The rtiddsgen tool is part of the RTI Connext DDS distribution.
--  For more information, type 'rtiddsgen -help' at a command shell
--  or consult the Code Generator User's Manual.
--
--  ============================================================================

pragma Extensions_Allowed (On);
with DDS;
with DDS.Sequences_Generic;

use type Standard.DDS.Long_Long;
use type Standard.DDS.Long;
use type Standard.DDS.Double;

pragma Style_Checks (off); --  Since this is autogenerated code.
package  Constants_IDL_File is


PI : constant Standard.DDS.Double := 3.1415;

PI2 : constant Standard.DDS.Double := 2.0*(PI);
 
    type MYLONG is new Standard.DDS.Long;
   type MYLONG_Access is access all MYLONG;
   pragma No_Strict_Aliasing (MYLONG_Access);
   type MYLONG_Array is array (Standard.DDS.Natural range <>) of aliased MYLONG;
   pragma Convention (C, MYLONG_Array);
 
   function MYLONG_Get_TypeCode return Standard.DDS.TypeCode_Access;
   pragma Import (C, MYLONG_Get_TypeCode, "MYLONG_get_typecode");

   procedure Initialize (This : in out MYLONG);
   procedure Finalize (This : in out MYLONG);
   procedure Copy (Dst : in out MYLONG;
                   Src : in MYLONG);
                 
   package MYLONG_Seq is new Standard.DDS.Sequences_Generic
   (Constants_IDL_File.MYLONG,
    Constants_IDL_File.MYLONG_Access,
    Standard.DDS.Natural,
    1,
    Constants_IDL_File.MYLONG_Array);               

LONG_CONST_123 : constant Constants_IDL_File.MYLONG := 100+23;

MY_STRING : constant Standard.DDS.String := Standard.DDS.To_DDS_String (" Hello World!");

LONG_LONG_CONST : constant Standard.DDS.Long_Long := 2147483648;

LONG_LONG_CONST2 : constant Standard.DDS.Long_Long := -2147483649;

LONG_CONST : constant Standard.DDS.Long := 2147483647;

LONG_CONST2 : constant Standard.DDS.Long := -2147483648;

end Constants_IDL_File;

