--  ============================================================================
--
--         WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.
--
--  This file was generated from Hello.idl
--  using RTI Code Generator (rtiddsgen) version 4.7.0.
--  The rtiddsgen tool is part of the RTI Connext DDS distribution.
--  For more information, type 'rtiddsgen -help' at a command shell
--  or consult the Code Generator User's Manual.
--
--  ============================================================================

pragma Extensions_Allowed (On);
with DDS;
with DDS.Sequences_Generic;


pragma Style_Checks (off); --  Since this is autogenerated code.
package  Hello is

 
  Time_TypeName : aliased Standard.DDS.String := Standard.DDS.To_DDS_String  ("Hello::Time");
   type Time is record
    seconds : aliased Standard.DDS.Unsigned_Long_Long;    
    fraction : aliased Standard.DDS.Unsigned_Long;    
   end record;
 
   pragma Convention (C, Time);
   type Time_Access is access all Time;
   pragma No_Strict_Aliasing (Time_Access);
   type Time_Array is array (Standard.DDS.Natural range <>) of aliased Time;
   pragma Convention (C, Time_Array);
 
   function Time_Get_TypeCode return Standard.DDS.TypeCode_Access;
   pragma Import (C, Time_Get_TypeCode, "Hello_Time_get_typecode");

   procedure Initialize (This : in out Time);
   procedure Finalize (This : in out Time);
   procedure Copy (Dst : in out Time;
                   Src : in Time);
                 
   package Time_Seq is new Standard.DDS.Sequences_Generic
   (Hello.Time,
    Hello.Time_Access,
    Standard.DDS.Natural,
    1,
    Hello.Time_Array);               

end Hello;

