--  ============================================================================
--
--         WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.
--
--  This file was generated from module.idl
--  using RTI Code Generator (rtiddsgen) version 4.7.0.
--  The rtiddsgen tool is part of the RTI Connext DDS distribution.
--  For more information, type 'rtiddsgen -help' at a command shell
--  or consult the Code Generator User's Manual.
--
--  ============================================================================

pragma Extensions_Allowed (On);
with DDS;
with DDS.Sequences_Generic;


pragma Style_Checks (off); --  Since this is autogenerated code.
package  a.b.c is

 
  foo_TypeName : aliased Standard.DDS.String := Standard.DDS.To_DDS_String  ("a::b::c::foo");
   type foo is record
    data : aliased Standard.DDS.Long;    
   end record;
 
   pragma Convention (C, foo);
   type foo_Access is access all foo;
   pragma No_Strict_Aliasing (foo_Access);
   type foo_Array is array (Standard.DDS.Natural range <>) of aliased foo;
   pragma Convention (C, foo_Array);
 
   function foo_Get_TypeCode return Standard.DDS.TypeCode_Access;
   pragma Import (C, foo_Get_TypeCode, "a_b_c_foo_get_typecode");

   procedure Initialize (This : in out foo);
   procedure Finalize (This : in out foo);
   procedure Copy (Dst : in out foo;
                   Src : in foo);
                 
   package foo_Seq is new Standard.DDS.Sequences_Generic
   (a.b.c.foo,
    a.b.c.foo_Access,
    Standard.DDS.Natural,
    1,
    a.b.c.foo_Array);               

end a.b.c;

