--  ============================================================================
--
--         WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.
--
--  This file was generated from base.idl
--  using RTI Code Generator (rtiddsgen) version 4.7.0.
--  The rtiddsgen tool is part of the RTI Connext DDS distribution.
--  For more information, type 'rtiddsgen -help' at a command shell
--  or consult the Code Generator User's Manual.
--
--  ============================================================================

pragma Extensions_Allowed (On);
with DDS;
with DDS.Sequences_Generic;


pragma Style_Checks (off); --  Since this is autogenerated code.
package  vtypes_test.base is

 
  position_t_TypeName : aliased Standard.DDS.String := Standard.DDS.To_DDS_String  ("vtypes_test::base::position_t");
   type position_t is record
    latitude : aliased Standard.DDS.Double;    
    longitude : aliased Standard.DDS.Double;    
    altitude : aliased Standard.DDS.Double;    
   end record;
 
   pragma Convention (C, position_t);
   type position_t_Access is access all position_t;
   pragma No_Strict_Aliasing (position_t_Access);
   type position_t_Array is array (Standard.DDS.Natural range <>) of aliased position_t;
   pragma Convention (C, position_t_Array);
 
   function position_t_Get_TypeCode return Standard.DDS.TypeCode_Access;
   pragma Import (C, position_t_Get_TypeCode, "vtypes_test_base_position_t_get_typecode");

   procedure Initialize (This : in out position_t);
   procedure Finalize (This : in out position_t);
   procedure Copy (Dst : in out position_t;
                   Src : in position_t);
                 
   package position_t_Seq is new Standard.DDS.Sequences_Generic
   (vtypes_test.base.position_t,
    vtypes_test.base.position_t_Access,
    Standard.DDS.Natural,
    1,
    vtypes_test.base.position_t_Array);               
 
  speed_t_TypeName : aliased Standard.DDS.String := Standard.DDS.To_DDS_String  ("vtypes_test::base::speed_t");
   type speed_t is record
    x : aliased Standard.DDS.Double;    
    y : aliased Standard.DDS.Double;    
    z : aliased Standard.DDS.Double;    
   end record;
 
   pragma Convention (C, speed_t);
   type speed_t_Access is access all speed_t;
   pragma No_Strict_Aliasing (speed_t_Access);
   type speed_t_Array is array (Standard.DDS.Natural range <>) of aliased speed_t;
   pragma Convention (C, speed_t_Array);
 
   function speed_t_Get_TypeCode return Standard.DDS.TypeCode_Access;
   pragma Import (C, speed_t_Get_TypeCode, "vtypes_test_base_speed_t_get_typecode");

   procedure Initialize (This : in out speed_t);
   procedure Finalize (This : in out speed_t);
   procedure Copy (Dst : in out speed_t;
                   Src : in speed_t);
                 
   package speed_t_Seq is new Standard.DDS.Sequences_Generic
   (vtypes_test.base.speed_t,
    vtypes_test.base.speed_t_Access,
    Standard.DDS.Natural,
    1,
    vtypes_test.base.speed_t_Array);               
 
  basetrack_t_TypeName : aliased Standard.DDS.String := Standard.DDS.To_DDS_String  ("vtypes_test::base::basetrack_t");
   type basetrack_t is record
    trackno : aliased Standard.DDS.String; --  maximum length = (10)    
    position : aliased vtypes_test.base.position_t;    
    speed : aliased vtypes_test.base.speed_t;    
    callsign : aliased Standard.DDS.String; --  maximum length = (32)    
   end record;
 
   pragma Convention (C, basetrack_t);
   type basetrack_t_Access is access all basetrack_t;
   pragma No_Strict_Aliasing (basetrack_t_Access);
   type basetrack_t_Array is array (Standard.DDS.Natural range <>) of aliased basetrack_t;
   pragma Convention (C, basetrack_t_Array);
 
   function basetrack_t_Get_TypeCode return Standard.DDS.TypeCode_Access;
   pragma Import (C, basetrack_t_Get_TypeCode, "vtypes_test_base_basetrack_t_get_typecode");

   procedure Initialize (This : in out basetrack_t);
   procedure Finalize (This : in out basetrack_t);
   procedure Copy (Dst : in out basetrack_t;
                   Src : in basetrack_t);
                 
   package basetrack_t_Seq is new Standard.DDS.Sequences_Generic
   (vtypes_test.base.basetrack_t,
    vtypes_test.base.basetrack_t_Access,
    Standard.DDS.Natural,
    1,
    vtypes_test.base.basetrack_t_Array);               

end vtypes_test.base;

