--  ============================================================================
--
--         WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.
--
--  This file was generated from base.idl
--  using RTI Code Generator (rtiddsgen) version 4.7.0.
--  The rtiddsgen tool is part of the RTI Connext DDS distribution.
--  For more information, type 'rtiddsgen -help' at a command shell
--  or consult the Code Generator User's Manual.
--
--  ============================================================================

pragma Extensions_Allowed (On);
pragma Warnings (Off); --  Since this is autogenerated code.
pragma Style_Checks (off);
pragma Extensions_Allowed (On);

with DDS;
with DDS.DomainParticipant;
with DDS.TypeSupport;
with DDS.DataReader;
with DDS.DataWriter;
with DDS.Treats_Generic;
with DDS.MetpTypeSupport_None;
with System;
package vtypes_test.base.basetrack_t_TypeSupport is

   type Ref is new Standard.DDS.TypeSupport.Ref with null record;
   type Ref_Access is access all Ref'Class;

   function Create_TypedDataReaderI
     (Self : access Ref) return Standard.DDS.DataReader.Ref_Access;

   procedure Destroy_TypedDataReaderI
     (Self   : access Ref;
      Reader : in out Standard.DDS.DataReader.Ref_Access);

   function Create_TypedDataWriterI
     (Self : access Ref) return Standard.DDS.DataWriter.Ref_Access;

   procedure Destroy_TypedDataWriterI
     (Self   : access Ref;
      Writer : in out Standard.DDS.DataWriter.Ref_Access);

   --  static methods

   procedure Register_Type
     (Participant :  not null access Standard.DDS.DomainParticipant.Ref'Class;
      Type_Name   : in Standard.DDS.String);

   procedure Unregister_Type
     (Participant : not null access Standard.DDS.DomainParticipant.Ref'Class;
      Type_Name   : in Standard.DDS.String);

   function Get_Type_Name return Standard.DDS.String;

   function Create_Data (AllocatePointers : in Boolean := True)
     return not null basetrack_t_Access;

   procedure Delete_Data
     (A_Data : in out basetrack_t_Access; DeletePointers : in Boolean := True);

   procedure Print_Data (A_Data : not null access constant basetrack_t);

   procedure Copy_Data
     (Dest   : not null access basetrack_t;
      Source : not null access constant basetrack_t);

   procedure Initialize_Data
     (Dest             : not null access basetrack_t;
      AllocatePointers : in Boolean := True);

   procedure Finalize_Data
     (Dest           : not null access basetrack_t;
      DeletePointers : in Boolean := True);

   procedure Finalize;

   package basetrack_t_Treats is new
     Standard.DDS.Treats_Generic (Data_Type        => basetrack_t,
                                  Data_Type_Access => basetrack_t_Access,
                                  Index_Type       => Standard.DDS.Natural,
                                  First_Element    => 1,
                                  Data_Array       => basetrack_t_Array,
                                  Initialize       => Initialize,
                                  Finalize         => Finalize,
                                  Copy             => Copy,
                                  Data_Sequences   => basetrack_t_Seq,
                                  Get_Type_Name    => Get_Type_Name,
                                  TypeSupport      => Ref,
                                  MetpTypeSupport  => Standard.DDS.MetpTypeSupport_None.Ref);

end vtypes_test.base.basetrack_t_TypeSupport;
